server:
  port: 9001

spring:
  application:
    name: feign-consumer
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

# feign 配置
feign:
  hystrix:
    enabled: false  # 关闭hystrix֧功能
  compression: # 请求和响应进行压缩
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/xml,application/xml,application/json
    response:
      enabled: true

# hystrix全局配置
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000
    hello:  # hystrixָ 通过方法名作为<Commandkey>来进行配置
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000




# ribbonָ 指定服务配置
HELLO-SERVICE:
  ribbon:
    ReadTimeout: 2000

# ribbon 全局配置
ribbon:
  ConnectTimeout: 250
  ReadTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1

# 日志
logging:
  file: logs/${spring.application.name}.log
  level.com.study.springcloud: DEBUG

